<?php
$settings=array();
$settings["dn_flag"]=1;
$settings["run_stats"]=1;
$settings["scan_int"]=9000;
$settings["FAILED"]="_FAILED_";
$settings["shows_dir"]="/mnt/media/Shows/";
$settings["dn_nzb_tmp"]="/mnt/data/NZB_TMP/";
$settings["dn_dir"]="/mnt/temp/NZB_AutoDownload/";
$settings["done_dir"]="/mnt/temp/NZB_Finished_Unsorted/";
$settings["faild_copy_log"]="logs/faild_copy.log";
$settings["copy_log"]="logs/copy.log";
$settings["failed_file"]="arrays/failed_shows_list.php";
$settings["failed_copy_file"]="arrays/failed_copy.php";
$settings["shows_file"]="arrays/shows_list.php";
$settings["shows_details"]="arrays/shows_details.php";
$settings["shows_newest"]="arrays/Shows_newest.php";
$settings["downloaded_nzbs"]="arrays/downloaded_nzbs.php";
$settings["raw_playlist"]="arrays/shows_playlist_raw.php";
$settings["shows_playlist"]="/mnt/media/Shows.asx";
$settings["username"]="";
$settings["API_KEY"]="";
$settings["SAB_API_Key"]="";
$settings["SAB_Host"]="172.16.1.15";
$settings["SAB_Port"]=8080;
$settings["last_scan"]=1295483731;
?>