<?php
$settings=array();
$settings["dn_flag"]=1;
$settings["run_stats"]=1;
$settings["scan_int"]=9000;
$settings["FAILED"]="_FAILED_";
$settings["shows_dir"]="Z:/Shows/";
$settings["dn_nzb_tmp"]="Z:/NZB_TMP/";
$settings["dn_dir"]="Z:/NZB_AutoDownload/";
$settings["done_dir"]="Z:/NZB_Finished_Unsorted/";
$settings["failed_file"]="arrays/failed_shows_list.txt";
$settings["failed_copy_file"]="arrays/failed_copy.txt";
$settings["shows_file"]="arrays/shows_list.txt";
$settings["shows_details"]="arrays/shows_details.txt";
$settings["shows_newest"]="arrays/Shows_newest.txt";
$settings["downloaded_nzbs"]="arrays/downloaded_nzbs.txt";
$settings["raw_playlist"]="arrays/shows_playlist_raw.txt";
$settings["shows_playlist"]="Z:/Shows.asx";
$settings["username"]="";
$settings["API_KEY"]="";
$settings["SAB_API_Key"]="";
$settings["SAB_Host"]="172.16.1.15";
$settings["SAB_Port"]=8080;
$settings["last_scan"]=1294982227;
?>